version: '3.8'

services:
  frontend:
    image: your-dockerhub-username/my-app-frontend:latest
    ports:
      - "3000:80"
    restart: always

  backend:
    image: your-dockerhub-username/my-app-backend:latest
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=mongodb://mongo:27017/mydb
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
